// Copyright 2019 The UNICORE Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file
//
// Author: Gaulthier Gain <gaulthier.gain@uliege.be>

package buildtool

// Exported const representing micro-libs definitions.
const (
	CARES             = "c-ares"
	COMPILERRT        = "compiler-rt"
	DEVFS             = "devfs"
	DPDK              = "dpdk"
	EIGEN             = "eigen"
	FP16              = "fp16"
	FXDIV             = "fxdiv"
	INTELINTRINSICS   = "intel-intrinsics"
	LIBAXTLS          = "libaxtls"
	LIBBLOCK          = "libblock"
	LIBCXX            = "libcxx"
	LIBCXXABI         = "libcxxabi"
	LIBGO             = "libgo"
	LIBJVM            = "libjvm"
	LIBPROC           = "libproc"
	LIBRUBY           = "libruby"
	LIBRUST           = "librust"
	LIBUKSCHEDPREEMPT = "libukschedpreempt"
	LIBUNWIND         = "libunwind"
	LIBUUID           = "libuuid"
	LIBUV             = "libuv"
	LIBV8             = "libv8"
	LWIP              = "lib-lwip"
	MICROPYTHON       = "micropython"
	MUSL              = "lib-musl"
	NEWLIB            = "lib-newlib"
	NOBLIM            = "noblim"
	NOLIBC            = "nolibc"
	OPENSSL           = "lib-openssl"
	PFS9              = "9pfs"
	POSIXLIBDL        = "posix_libdl"
	POSIXPROCESS      = "posix_process"
	POSIXUSER         = "posix_user"
	POSIXSYSINFO      = "posix_sysinfo"
	PTHREADEMBEDDED   = "lib-pthread-embedded"
	PTHREADPOOL       = "lib-pthreadpool"
	PYTHON            = "python"
	RAMFS             = "ramfs"
	SYSCALLSHIM       = "syscallshim"
	UKALLOC           = "ukalloc"
	UKALLOCBBUDDY     = "ukallocbbuddy"
	UKARGPARSE        = "ukargparse"
	UKBOOT            = "ukboot"
	UKBUS             = "ukbus"
	UKDEBUG           = "ukdebug"
	UKLOCK            = "uklock"
	UKMPI             = "ukmpi"
	UKMMAP            = "ukmmap"
	UKSIGNAL          = "uksignal"
	UKNETDEV          = "uknetdev"
	UKPCI             = "ukpci"
	UKSCHED           = "uksched"
	UKSCHEDCOOP       = "ukschedcoop"
	UKSGLIST          = "uksglist"
	UKSYSINFO         = "uksysinfo"
	UKSWRAND          = "ukswrand"
	UKTIMECONV        = "uktimeconv"
	UKTIME            = "uktime"
	VFSCORE           = "vfscore"
	ZLIB              = "lib-zlib"
)
